version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./.docker/dotnet/Dockerfile.dotnet
    container_name: devlooppearDotNet
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # # Nginx reverse proxy
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./.docker/nginx/Dockerfile.nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app
  #   # Restart policy to ensure that NGINX restarts if the app restarts
  #   restart: always
